name: Build and test

on:
  pull_request:
  push:
    branches:
      - ros2

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install missing dependencies
      run: sudo apt update && rosdep update && DEBIAN_FRONTEND=noninteractive rosdep install --from-paths . --ignore-src --rosdistro foxy -y

    - name: Build
      run: . /opt/ros/foxy/setup.sh && colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: . /opt/ros/foxy/setup.sh && colcon test --event-handlers console_cohesion+
